### ISSUE TITLE
Suggestions/Corrections to agent-design document

### ISSUE THREAD

**Issue by mhailstone** [PSPC-SPAC-buyandsell/von_base#1]
After my initial reading of the document, I have identified a few corrections and suggestions that would have helped me follow the documentation more easily:
* In line 92 on page 6, remove the word "the" from "...an indy-sdk prover, the a client POSTs..."
* In line 101 on page 6, insert the word "of" such as "...allows for zero or more of a claim issue and storage operations..."
* In line 127 on page 7, insert the word "to" such as "...proxy, to a client’s POSTed proof-request message..."
* In line 134 on page 7, insert the word "to" such as "...proxy, a client’s POSTed verification-request message..."
* In line 139 on page 7, remove the word "to" from "The API takes to a GET request on path api/v0/txn/<seq-no>..."
* In line 145 on page 7, insert a space after the period in "network.In the event..."
* In line 173 on page 8, surround JSON key names in quotations such as "The "did" component of the "agent-nym" json-dict..."
* In line 184 on page 9, surround JSON key names in quotations such as "where the "dest" content holds the agent DID, "verkey" content holds its verification key, and "identifier" content holds the DID"
* In line 200 on page 9, surround JSON key names in quotations such as "If "proxy-did" is specified and distinct..."
* In line 204 on page 9, surround JSON key names in quotations such as "The "did" and "verkey" components of the "agent-nym" json-dict specify the DID..."
* In line 221 on page 9, surround JSON key names in quotations such as "The "did" component of the "agent-endpoint" json-dict specifies the DID..."
* In line 238 on page 10, surround JSON key names in quotations such as "If "proxy-did" is specified and distinct from the underlying agent's DID..."
* In line 302 on page 12, surround JSON key names in quotations such as "If "schema" is specified, it overrides any schema that..."
* In line 341 on page 13, surround JSON key names in quotations such as "If "proxy-did" is specified and distinct from the underlying..."
* In line 345 on page 13, surround JSON key names in quotations such as "If "schema" is specified, it overrides any schema that..."
* In line 362 on page 13, surround JSON key names in quotations such as "The content of "claim-req" comes from..."
* In line 363 on page 13, surround JSON key names in quotations such as "The json-dict content of "claim-attrs" comprises..."
* In line 383 on page 14, surround JSON key names in quotations such as "If "proxy-did" is specified and distinct from..."
* In line 416 on page 14, surround JSON key names in quotations such as "If "proxy-did" is specified and distinct from..."
* In line 418 on page 14, surround JSON key names in quotations such as "If "schema" is specified, it overrides any schema..."
* In line 420 on page 15, surround JSON key names in quotations such as "The json-dict content of "attr-match" comprises..."
* In line 439 on page 15, surround JSON key names in quotations such as "with the "proof-req" value holding the proof request... and values, and the "claims" lists all claims"
* In line 488 on page 16, surround JSON key names in quotations such as "If "proxy-did" is specified and distinct from..."
* In line 490 on page 16, surround JSON key names in quotations such as "If "schema" is specified, it overrides any schema..."
* In line 492 on page 16, surround JSON key names in quotations such as "The json-dict content of "attr-match" comprises the attribute-value pairs..."
* In line 496 on page 16, surround JSON key names in quotations such as "The json-list content of "predicate-match" specifies zero..."
* In line 506 on page 17, surround JSON key names in quotations such as "with the "proof-req" value holding the proof request to use in subsequent messages and values, and the "proof" content houses"
* In line 527 on page 17, surround JSON key names in quotations such as "If "proxy-did" is specified and distinct from..."
* In line 529 on page 17, surround JSON key names in quotations such as "If "schema" is specified, it overrides any schema..."
* In line 531 on page 17, surround JSON key names in quotations such as "The json-str content of "claim-uuid" specifies..."
(An update in MS Word re-ordered my numbers, so I'm not sure how the above may align still.)

**Comment by sklump** [comment]
Thanks, I only just noticed this now.

I will carry corrections through future releases.
